"""
Django settings for labelwechatalt project.

Generated by 'django-admin startproject' using Django 1.10.7.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'lojdwoj=2d&7(^p!t)p#i&!-+7m0@-()oa1e_4wt1$ypk0b_2#'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'wechat.apps.WechatConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
]

ROOT_URLCONF = 'labelwechatalt.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'labelwechatalt.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/wechatstatic/'

INIT_DATA_DIR = 'e:/data/wechat/anno/'

ARTICLES_FILE = os.path.join(INIT_DATA_DIR, 'hard_articles.json')
MENTIONS_FILE = os.path.join(INIT_DATA_DIR, 'hard_article_mentions.json')
ACCOUNT_INFO_FILE = os.path.join(INIT_DATA_DIR, 'account_nickname.csv')

ACR_NAME_FILE = os.path.join(INIT_DATA_DIR, 'acr_name_filter.txt')
EXTRA_ACR_NAME_FILE = os.path.join(INIT_DATA_DIR, 'acr_name_man.txt')
EXPANSION_EXCLUDE_STRS_FILE = os.path.join(INIT_DATA_DIR, 'expansion_exclude_strs.txt')
ABBREV_EXCLUDE_STRS_FILE = os.path.join(INIT_DATA_DIR, 'abbrev_exclude_strs.txt')

ACCOUNT_NICKNAME_FILE = os.path.join(INIT_DATA_DIR, 'account_nickname.csv')
ACCOUNT_NAME_WORDS_FILE = os.path.join(INIT_DATA_DIR, 'account_nicknames_seg.txt')
WORD_NAME_FILE = os.path.join(INIT_DATA_DIR, 'word_to_name.txt')
WORD_IDF_FILE = os.path.join(INIT_DATA_DIR, 'word_idf.txt')
JIEBA_DICT_FILE = os.path.join(INIT_DATA_DIR, 'dict_fixed.txt')

ES_URL = '127.0.0.1:9200'
